### ISSUE TITLE
How is the .envrc working?

### ISSUE THREAD

**Issue by ShivamJoker** [NordicSemiconductor/asset-tracker-cloud-memfault-aws-js#6]
I couldn't find the code where you are loading the variables in the environment, is it automatically done by AWS cli ?

**Comment by coderbyheart** [comment]
Hei,

no, this works because of [direnv](https://direnv.net/). We've documented the setup [here](https://nordicsemiconductor.github.io/asset-tracker-cloud-docs/saga/docs/guides/Direnv.html#about-direnv).
